export default{
    tipKorisnika:'',
    authenticated: false,
    searchTerm:'',
    userEmail:'',
    podaci:[],
    url:'',
    mojipodaci:[],
    profil:[],
    aktivnikorisnik: null,
    owo:[],
    korisnickipodaci:[],
    status:'',
    napomena:'',
    tekst:'',
    tipoglasa:[],
    status:'',
    podaci1:[],
    uwu:[],
    aktivnikorisnik:'',
    satnica:'',
    email:'',
    brtel:'',
    datumk:'',
    datum:'',
    grad:'',
    napomena:'',
    oib:'',
    poslodavac:'',
    putni:'',
    vrsta:'',
    prijava:'',
    prijave:[],
    prijave1:[],
    ocekivanje:'',
    status1:''
}